### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yqf2000119** [bufanzhao/point-cloud-completion#2]
您好，我在运行过程matlab报错显示在buliaomini中 函数或变量 'plane' 无法识别。
这是具体报错信息：
出错 buliaomoni (第 47 行)
buliao=[plane(:,1:2) repmat(zmax,size(plane,1),1) repmat(0,size(plane,1),1) repmat(1,size(plane,1),1) plane(:,3:4)];

出错 tianbu_guocheng (第 6 行)
[buliao_out_x1,data_out,high,data_out3]=buliaomoni(data_new,2,normal,juli,zhengping);

出错 main (第 38 行)
[data_new1,buliao_out_x1]=tianbu_guocheng(data_new,[1 0 0],'x1',5,2);，

然后我也没有在这个文件中找到plane的声明，向请教一下这里的错误是什么问题，非常感谢！

**Comment by bufanzhao** [comment]
您好！这里的plane的定义就在47行前面一个for循环（37-45行代码），构建的初始规则布料二维格网，47行再加上z轴变成三维布料格网。


 赵不钒
 ***@***.***
  



---- Replied Message ----
From  ***@***.***> Date  5/18/2024 15:37 To  ***@***.***> Cc  ***@***.***> Subject  [bufanzhao/point-cloud-completion] bug (Issue #2)  

您好，我在运行过程matlab报错显示在buliaomini中 函数或变量 'plane' 无法识别。
 这是具体报错信息：
 出错 buliaomoni (第 47 行)
 buliao=[plane(:,1:2) repmat(zmax,size(plane,1),1) repmat(0,size(plane,1),1) repmat(1,size(plane,1),1) plane(:,3:4)];
出错 tianbu_guocheng (第 6 行)
 [buliao_out_x1,data_out,high,data_out3]=buliaomoni(data_new,2,normal,juli,zhengping);
出错 main (第 38 行)
 [data_new1,buliao_out_x1]=tianbu_guocheng(data_new,[1 0 0],'x1',5,2);，
然后我也没有在这个文件中找到plane的声明，向请教一下这里的错误是什么问题，非常感谢！

**Comment by yqf2000119** [comment]
> 您好！这里的plane的定义就在47行前面一个for循环（37-45行代码），构建的初始规则布料二维格网，47行再加上z轴变成三维布料格网。 赵不钒 ***@***.***
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 5/18/2024 15:37 To ***@***.***> Cc ***@***.***> Subject [bufanzhao/point-cloud-completion] bug (Issue #2) 您好，我在运行过程matlab报错显示在buliaomini中 函数或变量 'plane' 无法识别。 这是具体报错信息： 出错 buliaomoni (第 47 行) buliao=[plane(:,1:2) repmat(zmax,size(plane,1),1) repmat(0,size(plane,1),1) repmat(1,size(plane,1),1) plane(:,3:4)]; 出错 tianbu_guocheng (第 6 行) [buliao_out_x1,data_out,high,data_out3]=buliaomoni(data_new,2,normal,juli,zhengping); 出错 main (第 38 行) [data_new1,buliao_out_x1]=tianbu_guocheng(data_new,[1 0 0],'x1',5,2);， 然后我也没有在这个文件中找到plane的声明，向请教一下这里的错误是什么问题，非常感谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

非常感谢您的回复，可能是我matlab版本较高，我用的是2023b的版本，可能里面有些不兼容。我刚刚重新在循环前声明了一个plane。我还想请教一下关于输入数据方面的问题，我使用的输入数据只包含了建筑物点，然后是规模比较大的一个建筑物群，但在中间运行过程中会有一些计算错误，就想问一下这种大规模而非单体的输入数据我是不是得分割一下再送入，还是直接送入前还需要处理一下。再次感谢您的回复！

**Comment by bufanzhao** [comment]
本文算法目前只能处理单体建筑。


 赵不钒
 ***@***.***
  



---- Replied Message ----
From  ***@***.***> Date  5/18/2024 16:38 To  ***@***.***> Cc  ***@***.***> ,
 ***@***.***> Subject  Re: [bufanzhao/point-cloud-completion] bug (Issue #2)  

您好！这里的plane的定义就在47行前面一个for循环（37-45行代码），构建的初始规则布料二维格网，47行再加上z轴变成三维布料格网。 赵不钒 @.***
 …
 ---- Replied Message ---- From @.> Date 5/18/2024 15:37 To @.> Cc @.> Subject [bufanzhao/point-cloud-completion] bug (Issue #2) 您好，我在运行过程matlab报错显示在buliaomini中 函数或变量 'plane' 无法识别。 这是具体报错信息： 出错 buliaomoni (第 47 行) buliao=[plane(:,1:2) repmat(zmax,size(plane,1),1) repmat(0,size(plane,1),1) repmat(1,size(plane,1),1) plane(:,3:4)]; 出错 tianbu_guocheng (第 6 行) [buliao_out_x1,data_out,high,data_out3]=buliaomoni(data_new,2,normal,juli,zhengping); 出错 main (第 38 行) [data_new1,buliao_out_x1]=tianbu_guocheng(data_new,[1 0 0],'x1',5,2);， 然后我也没有在这个文件中找到plane的声明，向请教一下这里的错误是什么问题，非常感谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>
非常感谢您的回复，可能是我matlab版本较高，我用的是2023b的版本，可能里面有些不兼容。我刚刚重新在循环前声明了一个plane。我还想请教一下关于输入数据方面的问题，我使用的输入数据只包含了建筑物点，然后是规模比较大的一个建筑物群，但在中间运行过程中会有一些计算错误，就想问一下这种大规模而非单体的输入数据我是不是得分割一下再送入，还是直接送入前还需要处理一下。再次感谢您的回复！

**Comment by yqf2000119** [comment]
> 本文算法目前只能处理单体建筑。 赵不钒 ***@***.***
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 5/18/2024 16:38 To ***@***.***> Cc ***@***.***> , ***@***.***> Subject Re: [bufanzhao/point-cloud-completion] bug (Issue #2) 您好！这里的plane的定义就在47行前面一个for循环（37-45行代码），构建的初始规则布料二维格网，47行再加上z轴变成三维布料格网。 赵不钒 @.*** … ---- Replied Message ---- From @.> Date 5/18/2024 15:37 To @.> Cc @.> Subject [bufanzhao/point-cloud-completion] bug (Issue #2) 您好，我在运行过程matlab报错显示在buliaomini中 函数或变量 'plane' 无法识别。 这是具体报错信息： 出错 buliaomoni (第 47 行) buliao=[plane(:,1:2) repmat(zmax,size(plane,1),1) repmat(0,size(plane,1),1) repmat(1,size(plane,1),1) plane(:,3:4)]; 出错 tianbu_guocheng (第 6 行) [buliao_out_x1,data_out,high,data_out3]=buliaomoni(data_new,2,normal,juli,zhengping); 出错 main (第 38 行) [data_new1,buliao_out_x1]=tianbu_guocheng(data_new,[1 0 0],'x1',5,2);， 然后我也没有在这个文件中找到plane的声明，向请教一下这里的错误是什么问题，非常感谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 非常感谢您的回复，可能是我matlab版本较高，我用的是2023b的版本，可能里面有些不兼容。我刚刚重新在循环前声明了一个plane。我还想请教一下关于输入数据方面的问题，我使用的输入数据只包含了建筑物点，然后是规模比较大的一个建筑物群，但在中间运行过程中会有一些计算错误，就想问一下这种大规模而非单体的输入数据我是不是得分割一下再送入，还是直接送入前还需要处理一下。再次感谢您的回复！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

感谢您的回复，我想再请教一下您论文中最后在一整个测试集上的补全效果是先将单个建筑补全然后将补全点加到测试数据集里进行合成得到的吗

**Comment by bufanzhao** [comment]
是的。


 赵不钒
 ***@***.***
  



---- Replied Message ----
From  ***@***.***> Date  5/18/2024 17:02 To  ***@***.***> Cc  ***@***.***> ,
 ***@***.***> Subject  Re: [bufanzhao/point-cloud-completion] bug (Issue #2)  

本文算法目前只能处理单体建筑。 赵不钒 @.***
 …
 ---- Replied Message ---- From @.> Date 5/18/2024 16:38 To @.> Cc @.> , @.> Subject Re: [bufanzhao/point-cloud-completion] bug (Issue #2) 您好！这里的plane的定义就在47行前面一个for循环（37-45行代码），构建的初始规则布料二维格网，47行再加上z轴变成三维布料格网。 赵不钒 @.*** … ---- Replied Message ---- From @.> Date 5/18/2024 15:37 To @.> Cc @.> Subject [bufanzhao/point-cloud-completion] bug (Issue #2) 您好，我在运行过程matlab报错显示在buliaomini中 函数或变量 'plane' 无法识别。 这是具体报错信息： 出错 buliaomoni (第 47 行) buliao=[plane(:,1:2) repmat(zmax,size(plane,1),1) repmat(0,size(plane,1),1) repmat(1,size(plane,1),1) plane(:,3:4)]; 出错 tianbu_guocheng (第 6 行) [buliao_out_x1,data_out,high,data_out3]=buliaomoni(data_new,2,normal,juli,zhengping); 出错 main (第 38 行) [data_new1,buliao_out_x1]=tianbu_guocheng(data_new,[1 0 0],'x1',5,2);， 然后我也没有在这个文件中找到plane的声明，向请教一下这里的错误是什么问题，非常感谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 非常感谢您的回复，可能是我matlab版本较高，我用的是2023b的版本，可能里面有些不兼容。我刚刚重新在循环前声明了一个plane。我还想请教一下关于输入数据方面的问题，我使用的输入数据只包含了建筑物点，然后是规模比较大的一个建筑物群，但在中间运行过程中会有一些计算错误，就想问一下这种大规模而非单体的输入数据我是不是得分割一下再送入，还是直接送入前还需要处理一下。再次感谢您的回复！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>
感谢您的回复，我想再请教一下您论文中最后在一整个测试集上的补全效果是先将单个建筑补全然后将补全点加到测试数据集里进行合成得到的吗

**Comment by yqf2000119** [comment]
> 是的。 赵不钒 ***@***.***
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 5/18/2024 17:02 To ***@***.***> Cc ***@***.***> , ***@***.***> Subject Re: [bufanzhao/point-cloud-completion] bug (Issue #2) 本文算法目前只能处理单体建筑。 赵不钒 @.*** … ---- Replied Message ---- From @.> Date 5/18/2024 16:38 To @.> Cc @.> , @.> Subject Re: [bufanzhao/point-cloud-completion] bug (Issue #2) 您好！这里的plane的定义就在47行前面一个for循环（37-45行代码），构建的初始规则布料二维格网，47行再加上z轴变成三维布料格网。 赵不钒 @.*** … ---- Replied Message ---- From @.> Date 5/18/2024 15:37 To @.> Cc @.> Subject [bufanzhao/point-cloud-completion] bug (Issue #2) 您好，我在运行过程matlab报错显示在buliaomini中 函数或变量 'plane' 无法识别。 这是具体报错信息： 出错 buliaomoni (第 47 行) buliao=[plane(:,1:2) repmat(zmax,size(plane,1),1) repmat(0,size(plane,1),1) repmat(1,size(plane,1),1) plane(:,3:4)]; 出错 tianbu_guocheng (第 6 行) [buliao_out_x1,data_out,high,data_out3]=buliaomoni(data_new,2,normal,juli,zhengping); 出错 main (第 38 行) [data_new1,buliao_out_x1]=tianbu_guocheng(data_new,[1 0 0],'x1',5,2);， 然后我也没有在这个文件中找到plane的声明，向请教一下这里的错误是什么问题，非常感谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 非常感谢您的回复，可能是我matlab版本较高，我用的是2023b的版本，可能里面有些不兼容。我刚刚重新在循环前声明了一个plane。我还想请教一下关于输入数据方面的问题，我使用的输入数据只包含了建筑物点，然后是规模比较大的一个建筑物群，但在中间运行过程中会有一些计算错误，就想问一下这种大规模而非单体的输入数据我是不是得分割一下再送入，还是直接送入前还需要处理一下。再次感谢您的回复！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***> 感谢您的回复，我想再请教一下您论文中最后在一整个测试集上的补全效果是先将单个建筑补全然后将补全点加到测试数据集里进行合成得到的吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

好的，非常感谢您的回复！

**Comment by yqf2000119** [comment]
您好，我在运行代码时遇到了如下的报错
位置 1 处的索引无效。数组索引必须为正整数或逻辑值。

出错 quedingbianjie (第 27 行)
        data1{i,j}=data(idxij==2,1:3);

出错 buliaomoni (第 23 行)
[data_out,xmin,xmax,ymin,ymax,zmax]=quedingbianjie(data_zhi,20);

出错 tianbu_guocheng (第 6 行)
[buliao_out_x1,data_out,high,data_out3]=buliaomoni(data_new,2,normal,juli,zhengping);

出错 main (第 62 行)
[data_new_out,buliao_out_x1]=tianbu_guocheng(data_new_in,directionx2,x2,k,1);
我运行的是文件中自带的B5文件中的数据，然后matlab版本为2021b，我想请问一下我没有其他修改的情况下报这个错误让我感到非常困惑。
